# Alternative app.yaml at root level for better detection
name: viaticos-2025
services:
- name: backend
  source_dir: backend
  github:
    repo: rodrigo-Upfront/viaticos2025
    branch: main
    deploy_on_push: true
  dockerfile_path: backend/Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  health_check:
    http_path: /api/health
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: JWT_ALGORITHM
    scope: RUN_TIME
    value: HS256

- name: frontend
  source_dir: frontend
  github:
    repo: rodrigo-Upfront/viaticos2025
    branch: main
    deploy_on_push: true
  dockerfile_path: frontend/Dockerfile
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: ${backend.PUBLIC_URL}/api

databases:
- name: viaticos-db
  engine: PG
  version: "15"
  production: false
