version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: viaticos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fast
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@database:5432/viaticos
      SECRET_KEY: your-super-secret-key-change-in-production-2024
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      EMAIL_ENABLED: true
    depends_on:
      - database
    ports:
      - "8000:8000"
    restart: unless-stopped
    # Optimized for faster rebuilds

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.fast
      args:
        REACT_APP_API_BASE_URL: http://161.35.39.205/api
    environment:
      REACT_APP_API_BASE_URL: http://161.35.39.205/api
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
