name: viaticos-2025
region: nyc
services:
  # Backend Service (FastAPI)
  - name: backend
    image:
      registry_type: DOCR
      repository: viaticos-backend
      tag: latest
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    health_check:
      http_path: /api/health
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_ALGORITHM
        scope: RUN_TIME
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "60"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        scope: RUN_TIME
        value: "7"
      - key: UPLOAD_PATH
        scope: RUN_TIME
        value: /app/storage/uploads
      - key: EXPORT_PATH
        scope: RUN_TIME
        value: /app/storage/exports
      - key: MAX_FILE_SIZE
        scope: RUN_TIME
        value: "10485760"

  # Frontend Service (React)
  - name: frontend
    image:
      registry_type: DOCR
      repository: viaticos-frontend
      tag: latest
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        scope: BUILD_TIME
        value: ${backend.PUBLIC_URL}/api

# Managed Database
databases:
  - name: viaticos-db
    engine: PG
    version: "15"
    production: false
    cluster_name: viaticos-cluster
    db_name: viaticos
    db_user: postgres
