name: viaticos-2025
region: nyc
services:
  # Backend Service (FastAPI)
  - name: backend
    build_command: cd backend && pip install -r requirements.txt
    dockerfile_path: backend/Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /api/health
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_ALGORITHM
        scope: RUN_TIME
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "60"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        scope: RUN_TIME
        value: "7"
      - key: UPLOAD_PATH
        scope: RUN_TIME
        value: /app/storage/uploads
      - key: EXPORT_PATH
        scope: RUN_TIME
        value: /app/storage/exports
      - key: MAX_FILE_SIZE
        scope: RUN_TIME
        value: "10485760"

  # Frontend Service (React)
  - name: frontend
    build_command: cd frontend && npm ci && npm run build
    dockerfile_path: frontend/Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        scope: BUILD_TIME
        value: ${_self.URL}/api
      - key: REACT_APP_UPLOAD_MAX_SIZE
        scope: BUILD_TIME
        value: "10485760"
      - key: GENERATE_SOURCEMAP
        scope: BUILD_TIME
        value: "false"

# Managed Database
databases:
  - name: viaticos-db
    engine: PG
    version: "15"
    production: false
    cluster_name: viaticos-cluster
    db_name: viaticos
    db_user: postgres
